version: "3.8"
services:
  backend:
    container_name: backend
    build: ./minerva-api
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    depends_on:
      - mysql
      - rabbitmq
  mysql:
    container_name: mysql
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_DATABASE}
    volumes:
      - database-volume:/var/lib/mysql
    ports:
      - "3310:3306"
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBIT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBIT_PASS}
    ports:
      - "5672:5672"
      - "15672:15672"
volumes:
  database-volume:
