spring.application.name=minerva-api

spring.web.resources.add-mappings=false

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://ep-billowing-math-acyi2ul7.sa-east-1.aws.neon.tech:5432/neondb?sslmode=require
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql: true

auth.jwt.token.secret=${TOKEN_SECRET}
session.expiration.time=3

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=minervaflashcards@gmail.com
spring.mail.password=${MAIL_PASS}

spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

frontend.url=https://minerva-flashcards.vercel.app